# Generated by Django 2.2 on 2019-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус')),
                ('date_of_completion', models.DateField(default=None, verbose_name='Дата выполнения')),
                ('full_description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Подробное описание')),
            ],
        ),
    ]
