# Generated by Django 2.2 on 2019-09-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='full_description',
        ),
    ]
