# Generated by Django 2.2 on 2019-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Подробное описание'),
        ),
    ]
