# Generated by Django 2.2 on 2019-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(default='', max_length=500, verbose_name='Подробное описание'),
        ),
    ]
