# Generated by Django 2.2 on 2019-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190909_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(default=None, max_length=500, verbose_name='Подробное описание'),
        ),
    ]
