# Generated by Django 2.2 on 2019-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190909_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='full_description',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateField(default=None, verbose_name='Дата выполнения'),
        ),
    ]
