# Generated by Django 2.2 on 2019-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190909_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Подробное описание'),
        ),
    ]
